#!/usr/bin/env bash
#./converter inputformat dmlc nytimes.train nytimes.test outputformat libsvm nytimes.vocab nytimes.libsvm.train nytimes.libsvm.test
./converter inputformat libsvm nytimes.vocab nytimes.libsvm.train nytimes.libsvm.test outputformat dmlc nytimes.train nytimes.test
